import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  Montserrat,
  Manrope,
  Reddit_Mono,
  Poppins,
  Eczar
} from 'next/font/google';
import './globals.css';
import '@/styles/print.css';
import { Toaster } from '@/components/ui/sonner';
import { AlertCircle } from 'lucide-react';
import { SessionProvider } from '@/components/auth/session-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin']
});

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin']
});

const redditMono = Reddit_Mono({
  variable: '--font-reddit-mono',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
});

const eczar = Eczar({
  variable: '--font-eczar',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Newon Inventory',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.png'
    // shortcut: "/logo.png",
    // apple: "/logo.png"
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${manrope.variable} ${redditMono.variable} ${poppins.variable} ${eczar.variable} antialiased bg-background text-foreground`}
      >
        <SessionProvider>
          {children}
          <Toaster
            position="bottom-right"
            richColors
            theme="light"
            visibleToasts={1}
            icons={{
              error: <AlertCircle className="h-4 w-4 text-destructive" />
            }}
          />
        </SessionProvider>
      </body>
    </html>
  );
}
