import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import '@/styles/print.css';
import { Toaster } from '@/components/ui/sonner';
import { AlertCircle } from 'lucide-react';
import { SessionProvider } from '@/components/auth/session-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Newon Inventory',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <SessionProvider>
          {children}
          <Toaster 
            position="bottom-right" 
            richColors 
            theme="light" 
            visibleToasts={1} 
            icons={{
              error: <AlertCircle className="h-4 w-4 text-destructive" />,
            }} 
          />
        </SessionProvider>
      </body>
    </html>
  );
}
