import type { Metadata } from 'next';
import {
  JetBrains_Mono,
  Manrope,
  Reddit_Mono,
  Tenor_Sans
} from 'next/font/google';
import './globals.css';
import '@/styles/print.css';
import { Toaster } from '@/components/ui/sonner';
import { AlertCircle } from 'lucide-react';
import { SessionProvider } from '@/components/auth/session-provider';

const jetbrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin']
});

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin']
});

const redditMono = Reddit_Mono({
  variable: '--font-reddit-mono',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
});

const tenorSans = Tenor_Sans({
  variable: '--font-tenor-sans',
  subsets: ['latin'],
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Newon Inventory',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.png'
    // shortcut: "/logo.png",
    // apple: "/logo.png"
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jetbrainsMono.variable} ${manrope.variable} ${redditMono.variable} ${tenorSans.variable} antialiased bg-background text-foreground`}
      >
        <SessionProvider>
          {children}
          <Toaster
            position="bottom-right"
            richColors
            theme="light"
            visibleToasts={1}
            icons={{
              error: <AlertCircle className="h-4 w-4 text-destructive" />
            }}
          />
        </SessionProvider>
      </body>
    </html>
  );
}
